services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      - PYTHONUNBUFFERED=1
      - VITE_API_URL=http://localhost
    restart: always

  frontend:
    build: .
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always